### ISSUE TITLE
Justera namn på endpoints

### ISSUE THREAD

**Issue by mattiaspalmqvist** [RI-SE/Eltariff-API#7]
- Lägg till version i path
- Byt namn för att tydliggöra att det är en sökning för POST-anropet
- Använd bara gemener och - i namnen

**Comment by larwa99** [comment]
Jag skulle även föreslå att vi tar bort "api" från path:en eftersom det försvårar samexistens med andra API:er. Detta pga av att de delar path och/eller att det blir en duplicering av "api" om det ingår i FQDN, t.ex. api.goteborgenergi.se/api/tariffs.

**Comment by mattiaspalmqvist** [comment]
Namn på endpoints är justerade
